#!/bin/bash

./Pods/SwiftLint/swiftlint lint --reporter json > swiftlint-report.json || false

if [ "$TRAVIS_PULL_REQUEST" != "false" ]
	echo 'Not in a pull request, skip report'
then
  bundle exec linterbot $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST < swiftlint-report.json
fi